version: '3.3'
services:
  mediashuttle:
    build:
      context: .
      dockerfile: ./Dockerfile
    # image: 2chella/epub2-3
    restart: always
    container_name: mediashuttle-dev
    ports:
      - "7000:80"
    volumes:
        - .:/application
        - ./index.php:/web/index.php
        - ./security.conf:/etc/apache2/conf-available/security.conf
        - ./site.conf:/etc/apache2/sites-available/000-default.conf
    command:
      - apachectl
      - "-D"
      - FOREGROUND