- url: /upload
  method: post
  routeBeforeInvoke:
    - util->keys
  invoke: package->upload
  return: json
- url: /download
  method: post
  routeBeforeInvoke:
    - util->keys
  invoke: package->download
  return: json
- url: /create
  method: post
  routeBeforeInvoke:
    - util->keys
  invoke: package->create
  return: json
- url: /
  method: get
  invoke: home->homePage
  return: raw
